### ISSUE TITLE
Returning null when trying to connect

### ISSUE THREAD

**Issue by MarcoIsNotReal** [EvoTM/gbxclient-node#2]
Hey,

I'm having this weird issue where I can't connect to my server, the host is good and same for the port but when I start my script it just doesn't do anything, I tried adding a .then after and log the result and it just says false. here's a code sample

```js
const { GbxClient } = require("@evotm/gbxclient");

const gbx = new GbxClient();

gbx.connect('blablabla', 5002).then(result => console.log(result));
gbx.call("SetApiVersion", "2013-04-16").then(result => console.log(result));
gbx.call("EnableCallbacks", true).then(result => console.log(result));

try {
    gbx.call("Authenticate", "SuperAdmin", "SuperAdmin").then(response => console.log(response));
} catch (e) {
    console.log("Authenticate to server failed.");
    process.exit(0);
}

// console output:
// false
```

Thank you for helping me :)

**Comment by reaby** [comment]
see readme.md for example how to use.

**Comment by MarcoIsNotReal** [comment]
Tried with the example too, same issue D:

**Comment by reaby** [comment]
Actually this is not even an issue, and I possible can't help you here. 
The library works as intented, you either do something wrong or your dedicated server is not setuped right.
Try asking #community-support at https://discord.gg/trackmania

**Comment by reaby** [comment]
First version of the code executes the code in wrong order:
![kuva](https://user-images.githubusercontent.com/1789509/144732164-587458c6-cd09-4f63-aa79-36742f50f491.png)

You really have to use async/await to keep the order of executing right:
![kuva](https://user-images.githubusercontent.com/1789509/144732178-f531e119-299a-47dd-a807-93973d196bff.png)
